### ISSUE TITLE
Highlighting persists when creating new Tasks.

### ISSUE THREAD

**Issue by oalejandro** [jbeaulieu/liszt#2] opened 2021-02-03 00:33 UTC

**Comment by jbeaulieu** [comment] 2021-02-06 02:20
Second manifestation of this issue occurs after deleting items. On occasion, new items will be highlighted when created and added to the list. This is probably caused by the same bug

**Comment by jbeaulieu** [comment] 2022-06-29 16:04
This bug might have the same root cause as #9, as it seems to have been resolved by undoing the merge of #8 into main.

**Closed by jbeaulieu** 2022-06-29 16:04 UTC
Labels: bug
